### ISSUE TITLE
#3 選択肢を自動生成したい

### ISSUE THREAD

**Issue by MiyamotoRin** [TakaminoRegent/advanced-AISpeculation#3]
現状、数百の単語リストからランダムに取得し、選択肢を生成するようにする

**Comment by MiyamotoRin** [comment]
generate_wordlistのブランチにプッシュした
問題としては、axiosで自動生成されたword_listはフロント側で取得されているが、
QuizDataに代入しても、なぜか選択肢に反映されない
一応QuizDataには格納されているのだが

**Comment by nabeman** [comment]
vue.jsではpushとpopとかを使わないと配列の値がリアクティブに変更されないらしい。
とりあえずforeachとpush関数を使ってリアクティブに反映されるようにした。ついでにword_listの初期値も空にした。
foreachを使わないスマートなやり方を見つけたら修正求む。マージはだれかお願いします

**Comment by MiyamotoRin** [comment]
あざっす！
